# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          #Get all pre-requisites
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              awscli==1.14.37
            # Login to ecr and docker login
            aws_login=`aws ecr get-login --no-include-email --region eu-west-2`
            eval $aws_login

            ls scripts

            sh scripts/create.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy
